version: '3.8'

services:
  db_mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  db_mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      GLIBC_TUNABLES: "glibc.pthread.rseq=0"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
  
  web:
    build: .
    container_name: django
    restart: always
    depends_on:
      - db_mysql
      - db_mongo
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate --no-input &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  mysql:
  mongo: